// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm_5hVSlCQwjOE-zLSmHgvqz2SzyALTBM',
    appId: '1:325683139946:web:d06a52f20d9923999a8113',
    messagingSenderId: '325683139946',
    projectId: 'habit-tracker-72a08',
    authDomain: 'habit-tracker-72a08.firebaseapp.com',
    storageBucket: 'habit-tracker-72a08.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfXT-yoNFCFd6ahN8hpOxIaM1ULKIh_Kw',
    appId: '1:325683139946:android:1591abdfc7a6b5699a8113',
    messagingSenderId: '325683139946',
    projectId: 'habit-tracker-72a08',
    storageBucket: 'habit-tracker-72a08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM4SVjCihbw0k2A9RKM9Yc2wYQxNSlS_c',
    appId: '1:325683139946:ios:7ff73130216f60d49a8113',
    messagingSenderId: '325683139946',
    projectId: 'habit-tracker-72a08',
    storageBucket: 'habit-tracker-72a08.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM4SVjCihbw0k2A9RKM9Yc2wYQxNSlS_c',
    appId: '1:325683139946:ios:7ff73130216f60d49a8113',
    messagingSenderId: '325683139946',
    projectId: 'habit-tracker-72a08',
    storageBucket: 'habit-tracker-72a08.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );
}